apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  type: LoadBalancer
  selector:
    app: achatfront
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80